### PR TITLE
add more purge endpoints for purge page

### PR DESCRIPTION
**Pull request by tom-james-watson**
There's now
```
/purge/all (all cdn and cache)
/purge/cdn/all
/purge/cdn/url {url: '/rss', [recursive: true]}
/purge/cache
```

### CODE REVIEW

**Comment by tom-james-watson** [comment]
[Let's add a purge section to the CMS...](https://trello.com/c/taSdB2eq/454-lets-add-a-purge-section-to-the-cms)

**Comment by chrisabrams** [comment]
Nice job!

**Comment by timbur** [comment]
So I was adding a page to the CMS for this and turns out we already have a page for it, albeit hidden and very outdated.  Said page also appears to use a `/cache` endpoint (https://github.com/f12/provide-paradigm-cache/blob/4f8b0f08a6e5a1ed1c8f0c90f7043635255c408b/src/index.js#L9) rather than `/purge`.  Is the `/cache` endpoint deprecated (`/purge` from here on)?

**Comment by chrisabrams** [comment]
Yes I think the /cache is dead.

**Pull request merged**
